### ISSUE TITLE
YubiKey mass enrollment crashs privacyidea command line tool

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyideaadm#29]
# Versions

privacyIDEA: trunk
Installation method:
- [x] from source / github
- [ ] in virtualenv
- [x] Debian
- [ ] Ubuntu
- more details:
OS: Debian Jessie
Webserver: NGINX / UWSGI

privacyideaadm: 2.15-1xenial
Installation method:
- [ ] from source / github
- [ ] in virtualenv
- [x] Debian
- [ ] Ubuntu
- more details:
OS: Debian

# What did you try to do?

While having an event action configured for yubikey initialization, the privacyidea (privacyideaadm) command line yubikey mass enrollment will successfully initialize a single yubikey token, but then crash with the following message:

```
...

Please insert the next yubikey. 
Found Yubikey with serial '...'

Traceback (most recent call last):
  File "/usr/bin/privacyidea", line 1563, in <module>
    main()
  File "/usr/bin/privacyidea", line 1557, in main
    args.func(args, client)
  File "/usr/bin/privacyidea", line 490, in yubikey_mass_enroll
    args.newaccess)
  File "/usr/bin/privacyidea", line 186, in yubi_mass_enroll
    resp = lotpc.inittoken(submit_param)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 164, in inittoken
    return self.post('/token/init', param)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 149, in post
    return self._send_response(r)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 101, in _send_response
    description=r.text)
privacyideautils.clientutils.PrivacyIDEAClientError: u'ERR500: {"jsonrpc": "2.0", "signature": "...", "detail": null, "version": "privacyIDEA unknown", "result": {"status": false, "error": {"message": "\'NoneType\' object has no attribute \'is_empty\'", "code": -500}}, "time": 1476956509.27276, "id": 1}'
```

When removing the event action, the mass enrollment process works fine.

**Comment by cornelinux** [comment]
Oh, "NoneType" "is_empty" looks like a user variable, which should contain a user object. Can you please take a look at the traceback in the privacyidea.log?

**Comment by berndnicklas** [comment]
```
[2016-10-20 12:01:48,304][26127][140440539084672][DEBUG][privacyidea.lib.eventhandler.usernotification:343] Executing event for action sendmail, user None,logged_in_user {'username': u'nicklasb', 'role': u'admin', 'realm': u'hrz-admin'}
[2016-10-20 12:01:48,305][26127][140440539084672][ERROR][privacyidea.app:1423] Exception on /token/init [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/prepolicy.py", line 109, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/api/lib/postpolicy.py", line 99, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/local/privacyidea/privacyidea/lib/event.py", line 78, in event_wrapper
    options=options)
  File "/local/privacyidea/privacyidea/lib/eventhandler/usernotification.py", line 348, in do
    if notify_type == NOTIFY_TYPE.TOKENOWNER and not tokenowner.is_empty():
AttributeError: 'NoneType' object has no attribute 'is_empty'
[2016-10-20 12:01:48,344][26127][140440539084672][INFO][privacyidea.api.lib.utils:56] We are not able to determine the privacyidea version number.
[2016-10-20 12:01:48,345][26127][140440539084672][DEBUG][privacyidea.api.lib.utils:239] Can not get param: No JSON object could be decoded
```
It's the tokenowner, which is not set on initialization.

**Comment by cornelinux** [comment]
Hm, close project does not work.
Please check the trunk of privacyidea server.
